import { openSans } from "./fonts";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`h-dvh bg-white text-gray-700 ${openSans.className} antialiased`}>
        <Header />
        <main className="py-12 sm:w-1/2 sm:mx-auto">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
